#!/usr/bin/env python3
"""
Description: Formatted 'following' of Apache log files
Usage:
    1. Add script to path or run it directly
    2. Flags:
        -a/--access = follow Apache's access.log
        -e/--error = follow Apache's error.log
"""

import argparse
import os
import re
import sys
import time

from dataclasses import dataclass

access_log = "/var/log/apache2/access.log"
error_log = "/var/log/apache2/error.log"

parser = argparse.ArgumentParser(prog='mali',
                                epilog='Hope you enjoy! :)',
                                description="ModSecurity Apache Log Inspector")

parser.add_argument('-a', '--access',
                    action='store_true',
                    help='Watch ' + access_log)

parser.add_argument('-e', '--error',
                    action='store_true',
                    help='Watch ' + error_log)

args = parser.parse_args()

if len(sys.argv) == 0:
    print("Please use -a, -e or -h flags")


@dataclass
class bcolors:
    """Color codes for colored output"""
    okblue: str = '\033[94m'
    okgreen: str = '\033[92m'
    warning: str = '\033[93m'
    error: str = '\033[91;1m'
    endc: str = '\033[0m'
    bold: str = '\033[1m'


def clear():
    """Clear the screen"""
    os.system('clear')


def tail(file, n=1, bs=1024):
    """Print lines of a file

    args:
        n: number of lines
        bs: block size

    returns:
        content of lines
    """
    with open(file, 'r', encoding='utf-8') as f:
        f.seek(0,2)
        l = f.read(1).count('\n')
        B = f.tell()
        while n >= l and B > 0:
            block = min(bs, B)
            B -= block
            f.seek(B, 0)
            l += f.read(block).count('\n')
        f.seek(B, 0)
        l = min(l,n)
        lines = f.readlines()[-l:]

    return lines


def access_parse():
    """Parse Apache access log

    Prints:
        formatted lines of the Apache access log
    """
    alines = tail(access_log, 10)

    for line in alines:
        alist = line.split(']')

        access_dict = {}
        for i in alist:
            strip = i.lstrip()
            if strip.startswith("["):
                strip = strip.replace('[', '')
                strip = strip.replace('"', '')
                (key,val) = strip.split(' ', 1)
                access_dict[key] = val

        print(f"{bcolors.bold}Request Time:{bcolors.endc} {access_dict['time']}")

        elines = tail(error_log, 15)
        uidcheck = ''.join(elines)
        if re.findall(access_dict['unique_id'], uidcheck):
            print(f"{bcolors.bold}Unique ID:{bcolors.endc} {bcolors.error}{access_dict['unique_id']}{bcolors.endc}")
        else:
            print(f"{bcolors.bold}Unique ID:{bcolors.endc} {access_dict['unique_id']}")

        print(
            f"{bcolors.bold}Remote Host:{bcolors.endc} {access_dict['remote_host']}\n"
            f"{bcolors.bold}User Agent:{bcolors.endc} {access_dict['remote_user_agent']}\n"
            f"{bcolors.bold}HTTP Referer:{bcolors.endc} {access_dict['http_referer']}\n"
            f"{bcolors.bold}HTTP Request:{bcolors.endc} {access_dict['http_request']}\n"
            f"{bcolors.bold}HTTP Status:{bcolors.endc} {access_dict['http_status']}\n"
            f"{bcolors.bold}SSL Protocol:{bcolors.endc} {access_dict['ssl_protocol']}\n"
            f"{bcolors.bold}SSL Cipher:{bcolors.endc} {access_dict['ssl_cipher']}\n"
        )


def error_parse():
    """Parse Apache error log

    Prints:
        formatted lines of the Apache error log
    """
    elines = tail(error_log, 20)
    for line in elines:
        if line.startswith('[time'):
            elist = line.split('] ')

            error_dict = {}
            for i in elist:
                lst = i.lstrip()
                if lst.startswith("["):
                    lst = lst.replace('[', '')
                    lst = lst.replace('"', '')
                    lst = lst.replace(']\n', '')
                    key, value = lst.split(' ', 1)

                if lst.startswith("ModSecurity"):
                    new = lst.split(' [')
                    for i in new:
                        lst = i.lstrip()
                        lst = lst.replace('"', '')
                        lst = lst.replace(':', '')
                        key, value = lst.split(' ', 1)

                error_dict[key] = value

                if "unique_id" in error_dict:
                    if "file" in error_dict:
                        print(
                            f"{bcolors.error}Time:{bcolors.endc} {error_dict['time']}\n"
                            f"{bcolors.error}Unique ID:{bcolors.endc} {error_dict['unique_id']}\n"
                            f"{bcolors.error}Remote Host:{bcolors.endc} {error_dict['client']}\n"
                            f"{bcolors.error}CRS Rule ID:{bcolors.endc} {error_dict['id']} ({error_dict['file']})\n"
                            f"{bcolors.error}HTTP Referer:{bcolors.endc} {error_dict['http_referer']}\n"
                            f"{bcolors.error}Client:{bcolors.endc} {error_dict['client']}"
                        )
                    else:
                        print(
                            f"{bcolors.error}CRS Rule ID:{bcolors.endc} {error_dict['id']}\n"
                            f"{bcolors.error}HTTP Referer:{bcolors.endc} {error_dict['http_referer']}\n"
                            f"{bcolors.error}Client:{bcolors.endc} {error_dict['client']}"
                        )
                    print(f"{bcolors.error}Msg:{bcolors.endc} {error_dict['msg']}")
                    if "severity" in error_dict:
                        print(f"{bcolors.error}Severity:{bcolors.endc} {error_dict['severity']}\n")
                    else:
                        print()


def monitor():
    """Check file modification time and follow the log file"""
    if args.access:
        log_file = access_log
    if args.error:
        log_file = error_log

    _cached_stamp = 0
    stamp = os.stat(log_file).st_mtime
    if stamp != _cached_stamp:
        # Clear the screen
        clear()

        # update timestamp
        _cached_stamp = stamp

        # Process last request in access.log
        if args.access:
            access_parse()

        # Process error requests
        if args.error:
            error_parse()


while True:
    try:
        time.sleep(1)
        monitor()
    except KeyboardInterrupt:
        print('\nDone')
        break
    except:
        print(f'Unhandled error: {sys.exc_info()}')

# vim: ft=python ts=4 sts=4 sw=4 nosr et
